### ISSUE TITLE
wrong route.length

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/kfactory#416]
https://github.com/gdsfactory/gdsfactory/issues/2950

**Comment by sebastian-goeldi** [comment]
fixed by https://github.com/gdsfactory/kfactory/commit/d6ef9cb75193f19eba4f3d64542b2de33b883462

**Comment by joamatab** [comment]
not really fixed

try this

```python
import gdsfactory as gf
import numpy as np
c = gf.Component()
waveguide_width = 1
ring_width = 1
ring_radius = 114
layer = (2,0)
couple_radius = 10
gap_up = 1
xs = gf.cross_section.cross_section(width=waveguide_width, layer=layer)
coupler1 = gf.path.arc(radius=couple_radius, start_angle=-90, angle=90)
coupler1 = c << (coupler1.extrude(xs))
coupler1.dmovey(-couple_radius)
coupler1.dmove(
    [(ring_radius + couple_radius + 0.5 * (ring_width + waveguide_width) + gap_up) * np.cos(135 / 180 * np.pi),
     (ring_radius + couple_radius + 0.5 * (ring_width + waveguide_width) + gap_up) * np.sin(135 / 180 * np.pi)])
coupler2 = gf.path.arc(radius=couple_radius, start_angle=-180, angle=90)
coupler2 = c << (coupler2.extrude(xs))
coupler2.dmovey(-couple_radius)
coupler2.dmove(
    [(ring_radius + couple_radius + 0.5 * (ring_width + waveguide_width) + gap_up) * np.cos(45 / 180 * np.pi),
     (ring_radius + couple_radius + 0.5 * (ring_width + waveguide_width) + gap_up) * np.sin(45 / 180 * np.pi)])
route = gf.routing.route_single(
    c,
    coupler1['o2'],
    coupler2['o1'],
    bend=gf.components.bend_circular,
    radius=-0.005 + 0.5 * abs(coupler1.ports['o2'].dx - coupler2.ports['o1'].dx),
    cross_section=xs,
)
print(route.length)
c.show()
```

the lenght should be around pi*80
